
my:
    greeting : Default
    list:
        values : one,two,three

db:
    connection : "{connectionString: default}"
    host : 1.0.0.0
    port : 1000

spring.profiles.active: test

management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: http://localhost:8888

spring.application.name: spring-boot-config-Default
